// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file messager.proto (package messager, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file messager.proto.
 */
export const file_messager: GenFile = /*@__PURE__*/
  fileDesc("Cg5tZXNzYWdlci5wcm90bxIIbWVzc2FnZXIiFQoEVVVJRBINCgV2YWx1ZRgBIAEoCSIUCgNVUkwSDQoFdmFsdWUYASABKAkiMQoPR2V0Q2hhdHNSZXF1ZXN0Eh4KBnVzZXJJZBgBIAEoCzIOLm1lc3NhZ2VyLlVVSUQiYwoMQ2hhdFJlc3BvbnNlEhoKAmlkGAEgASgLMg4ubWVzc2FnZXIuVVVJRBIMCgR0eXBlGAIgASgFEgwKBG5hbWUYAyABKAkSGwoEbG9nbxgEIAEoCzINLm1lc3NhZ2VyLlVSTDJOCgtDaGF0U2VydmljZRI/CghHZXRDaGF0cxIZLm1lc3NhZ2VyLkdldENoYXRzUmVxdWVzdBoWLm1lc3NhZ2VyLkNoYXRSZXNwb25zZTABQgZaBC4vcGJiBnByb3RvMw");

/**
 * @generated from message messager.UUID
 */
export type UUID = Message<"messager.UUID"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message messager.UUID.
 * Use `create(UUIDSchema)` to create a new message.
 */
export const UUIDSchema: GenMessage<UUID> = /*@__PURE__*/
  messageDesc(file_messager, 0);

/**
 * @generated from message messager.URL
 */
export type URL = Message<"messager.URL"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message messager.URL.
 * Use `create(URLSchema)` to create a new message.
 */
export const URLSchema: GenMessage<URL> = /*@__PURE__*/
  messageDesc(file_messager, 1);

/**
 * @generated from message messager.GetChatsRequest
 */
export type GetChatsRequest = Message<"messager.GetChatsRequest"> & {
  /**
   * @generated from field: messager.UUID userId = 1;
   */
  userId?: UUID | undefined;
};

/**
 * Describes the message messager.GetChatsRequest.
 * Use `create(GetChatsRequestSchema)` to create a new message.
 */
export const GetChatsRequestSchema: GenMessage<GetChatsRequest> = /*@__PURE__*/
  messageDesc(file_messager, 2);

/**
 * @generated from message messager.ChatResponse
 */
export type ChatResponse = Message<"messager.ChatResponse"> & {
  /**
   * @generated from field: messager.UUID id = 1;
   */
  id?: UUID | undefined;

  /**
   * @generated from field: int32 type = 2;
   */
  type: number;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: messager.URL logo = 4;
   */
  logo?: URL | undefined;
};

/**
 * Describes the message messager.ChatResponse.
 * Use `create(ChatResponseSchema)` to create a new message.
 */
export const ChatResponseSchema: GenMessage<ChatResponse> = /*@__PURE__*/
  messageDesc(file_messager, 3);

/**
 * @generated from service messager.ChatService
 */
export const ChatService: GenService<{
  /**
   * @generated from rpc messager.ChatService.GetChats
   */
  getChats: {
    methodKind: "server_streaming";
    input: typeof GetChatsRequestSchema;
    output: typeof ChatResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_messager, 0);

