// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/messager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_proto_messager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_proto_messager_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_proto_messager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_proto_messager_proto_rawDescGZIP(), []int{1}
}

func (x *URL) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *UUID                  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsRequest) Reset() {
	*x = GetChatsRequest{}
	mi := &file_proto_messager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsRequest) ProtoMessage() {}

func (x *GetChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsRequest.ProtoReflect.Descriptor instead.
func (*GetChatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_messager_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatsRequest) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Logo          *URL                   `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_messager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_messager_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ChatResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatResponse) GetLogo() *URL {
	if x != nil {
		return x.Logo
	}
	return nil
}

var File_proto_messager_proto protoreflect.FileDescriptor

const file_proto_messager_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messager.proto\x12\bmessager\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1b\n" +
	"\x03URL\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"9\n" +
	"\x0fGetChatsRequest\x12&\n" +
	"\x06userId\x18\x01 \x01(\v2\x0e.messager.UUIDR\x06userId\"y\n" +
	"\fChatResponse\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\v2\x0e.messager.UUIDR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\x04logo\x18\x04 \x01(\v2\r.messager.URLR\x04logo2N\n" +
	"\vChatService\x12?\n" +
	"\bGetChats\x12\x19.messager.GetChatsRequest\x1a\x16.messager.ChatResponse0\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_messager_proto_rawDescOnce sync.Once
	file_proto_messager_proto_rawDescData []byte
)

func file_proto_messager_proto_rawDescGZIP() []byte {
	file_proto_messager_proto_rawDescOnce.Do(func() {
		file_proto_messager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messager_proto_rawDesc), len(file_proto_messager_proto_rawDesc)))
	})
	return file_proto_messager_proto_rawDescData
}

var file_proto_messager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_messager_proto_goTypes = []any{
	(*UUID)(nil),            // 0: messager.UUID
	(*URL)(nil),             // 1: messager.URL
	(*GetChatsRequest)(nil), // 2: messager.GetChatsRequest
	(*ChatResponse)(nil),    // 3: messager.ChatResponse
}
var file_proto_messager_proto_depIdxs = []int32{
	0, // 0: messager.GetChatsRequest.userId:type_name -> messager.UUID
	0, // 1: messager.ChatResponse.id:type_name -> messager.UUID
	1, // 2: messager.ChatResponse.logo:type_name -> messager.URL
	2, // 3: messager.ChatService.GetChats:input_type -> messager.GetChatsRequest
	3, // 4: messager.ChatService.GetChats:output_type -> messager.ChatResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_messager_proto_init() }
func file_proto_messager_proto_init() {
	if File_proto_messager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messager_proto_rawDesc), len(file_proto_messager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messager_proto_goTypes,
		DependencyIndexes: file_proto_messager_proto_depIdxs,
		MessageInfos:      file_proto_messager_proto_msgTypes,
	}.Build()
	File_proto_messager_proto = out.File
	file_proto_messager_proto_goTypes = nil
	file_proto_messager_proto_depIdxs = nil
}
